version: "3.9"
services:
  mysql:
    container_name: goproject-dev-middleware-mysql
    image: mysql:5.7.41-debian
    restart: on-failure
    networks:
      - default
    ports:
      - "10010:3306"
    environment:
      - MYSQL_DATABASE=goproject
      - MYSQL_USER=goproject
      - MYSQL_PASSWORD=goproject
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    command: [mysqld, --character-set-server=utf8mb4]
  redis:
    container_name: goproject-dev-middleware-redis
    image: redis:6.2.11-bullseye
    restart: on-failure
    networks:
      - default
    ports:
      - "10011:6379"
networks:
  default:
    name: goproject-dev-middleware
