apiVersion: v1
kind: ConfigMap
metadata:
  namespace: middleware
  name: mysql
data:
  my.cnf: |
    [mysqld]
    user = mysql
    server-id = 1
    bind-address = 0.0.0.0
    datadir = /var/lib/mysql
    pid-file = /var/run/mysqld/mysqld.pid
    socket = /var/run/mysqld/mysqld.sock
    character-set-server=utf8mb4
    
    log-error = /var/log/mysql/error.log
    slow-query-log = TRUE
    slow-query-log-file = /var/log/mysql/slow.log
    long-query-time = 0.1
    log-queries-not-using-indexes = TRUE
    
    connect-timeout = 10
    wait-timeout = 36000
    interactive-timeout = 36000
    
    max-connections = 500
    max-allowed-packet = 8M
    thread-cache-size = 10
    thread-stack = 256K
    
    log-bin = mysql-bin
    binlog-format = ROW
    expire-logs-days = 10
    max-binlog-size = 1G
    binlog-row-image = MINIMAL
    binlog-do-db = goproject
    
    [mysql]
    default-character-set = utf8mb4
    
    [client]
    default-character-set = utf8mb4
