apiVersion: v1
kind: Pod
metadata:
  namespace: middleware
  name: redis
  labels:
    name: redis
spec:
  nodeSelector:
    middleware: "true"
  restartPolicy: Always
  containers:
    - name: redis
      image: redis:6.2.11-bullseye
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 6379
      command: [sh, -c, redis-server /etc/redis/redis.conf]
      livenessProbe:
        exec:
          command: [redis-cli, ping]
        initialDelaySeconds: 10
        periodSeconds: 10
        timeoutSeconds: 2
        successThreshold: 1
        failureThreshold: 3
      volumeMounts:
        - name: redis-config
          mountPath: /etc/redis/redis.conf
          subPath: redis.conf
        - name: redis-data
          mountPath: /data/redis
        - name: localtime
          mountPath: /etc/localtime
          readOnly: true
  volumes:
    - name: redis-config
      configMap:
        name: redis
    - name: redis-data
      hostPath:
        path: /data/redis
        type: Directory
    - name: localtime
      hostPath:
        path: /etc/localtime
        type: File
