apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: goproject
  name: goproject-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goproject-nginx
  template:
    metadata:
      labels:
        app: goproject-nginx
    spec:
      nodeSelector:
        goproject: "true"
      containers:
        - name: goproject-nginx
          image: DOCKER_REPOSITORY/goproject-nginx:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
            - containerPort: 443
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
          resources:
            limits:
              cpu: 2
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 512Mi
