environment:
debug: true
jwtKey:
apiServerAddr: :8000
userCenterRPCServerAddr: goproject-usercenter-rpc:8000
db:
  addr: goproject-mysql:3306
  user: goproject
  password: goproject
  database: goproject
redis:
  addr: goproject-redis:6379
  password:
