version: "3.9"
services:
  api:
    container_name: goproject-dev-server-api
    image: goproject-server
    restart: on-failure
    networks:
      - goproject-dev-middleware
    ports:
      - "10020:8000"
    environment:
      - GOPROJECT_SERVER_CONFIG_FILE=/etc/goproject/server.yaml
    command: [goproject-server, api]
  worker1:
    container_name: goproject-dev-server-worker1
    image: goproject-server
    restart: on-failure
    networks:
      - goproject-dev-middleware
    environment:
      - GOPROJECT_SERVER_CONFIG_FILE=/etc/goproject/server.yaml
    command: [goproject-server, worker1]
networks:
  goproject-dev-middleware:
    external: true
